### PR TITLE
add an AddFunc to handle finalizers in GC for initial lists/resyncs

### LINKED ISSUE #338: GC controller doesn't process backups deleted while ark server was offline
We need to have an AddFunc too

https://github.com/heptio/ark/blob/52641e8e29eb48f0516c34dee315d1d1001d7b7e/pkg/controller/gc_controller.go#L102

AddFunc will be called on the initial list and on any resyncs.

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <steve@heptio.com>

Fixes #338

### CODE REVIEW

**Comment by ncdc** [comment]
Might be worth making sure we have a unit test that fails without this fix

**Comment by ncdc** [comment]
@skriss can you do a unit test?

**Comment by skriss** [comment]
How do I write a unit test for this? By accessing the informer's store and `.Add()`ing an item to it?

**Comment by ncdc** [comment]
Let me look into it - it's been a while since I've done one of these

**Comment by ncdc** [comment]
Ok the easiest way to unit test this is to convert the entire GC controller to use a queue and allow the syncHandler to be overridden in the tests. I'll file an issue so we can take care of that later.

**Pull request merged**
