### PR TITLE
Remove timeout check for snapshot service

### LINKED ISSUE #921: Ark unable to restore PV/PVC from GCP snapshots
**What steps did you take and what happened:**

1 - Schedule a backup for the different namespaces of my GKE Cluster
2 - Recreated the cluster (i was needed in order to tune some settings that can´t be changed on an existing cluster, at least terraform can´t do it with a destroy/create)
3 - Installed ark in the new cluster, same version/settings than before with `restoreOnlyMode: true`
4 - Attempted to restore the backups using `ark restore create --from-backup`

**What did you expect to happen:**

All deployments/services/etc where restored, but some of the PVC failed

```
ark restore describe monitoring-20181010142353-20181010162853
Name:         monitoring-20181010142353-20181010162853
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Backup:  monitoring-20181010142353

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.ark.heptio.com, restores.ark.heptio.com
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Phase:  Completed

Validation errors:  <none>

Warnings:
  Ark:        <none>
  Cluster:    <none>
  Namespaces:
    monitoring:  not restored: replicasets.apps "grafana-547686c94f" already exists and is different from backed up version.
                 not restored: replicasets.apps "kube-state-metrics-7cd9c448b7" already exists and is different from backed up version.
                 not restored: replicasets.apps "prometheus-operator-586865c679" already exists and is different from backed up version.
                 not restored: replicasets.apps "stackdriver-exporter-6cdd796d" already exists and is different from backed up version.

Errors:
  Ark:        <none>
  Cluster:  error executing PVAction for /tmp/138742704/resources/persistentvolumes/cluster/pvc-0d9dd688-95d1-11e8-8d9a-42010a8e002d.json: timeout reached waiting for volume restore-147a1b68-3f92-4575-ac5c-687b0d18bdc5 to be ready
            error executing PVAction for /tmp/138742704/resources/persistentvolumes/cluster/pvc-f5a90019-95d0-11e8-8d9a-42010a8e002d.json: timeout reached waiting for volume restore-9e60e21e-640c-4648-af41-7596f008b415 to be ready
  Namespaces: <none>
```

And this is how the persistent volumes and disk look now on GCP

captura de pantalla 2018-10-10 a la s 16 38 51

captura de pantalla 2018-10-10 a la s 16 32 55

**Environment:**

- Ark version (use `ark version`):   0.9.7
- Kubernetes version (use `kubectl version`): v1.10.7
- Kubernetes installer & version: v1.10.6-gke.4
- Cloud provider or hardware configuration: GKE

### PR DESCRIPTION
**Pull request by carlisia**
Fixes #921 for a 0.9.x release.

### CODE REVIEW

**Comment by ncdc** [comment]
@carlisia if you wanted to, you could also remove the 2 now-unused constants in here.

**Comment by ncdc** [comment]
Gonna close/reopen to kick the checks

**Comment by carlisia** [comment]
Yep! let me remove those.

**Comment by carlisia** [comment]
Ready for another pass.

**Comment by skriss** [comment]
@carlisia looks like you need to signoff on the commit.  Otherwise LGTM

**Pull request merged**
