### PR TITLE
Restore storageclasses before pvs and pvcs

### LINKED ISSUE #594: Restore storageclasses before persistentvolumes and persistentvolumeclaims
This is necessary so the PVs and PVCs can be created correctly.

### PR DESCRIPTION
**Pull request by shubheksha**
Signed-off-by: Shubheksha Jalan <jshubheksha@gmail.com>
Fixes #594

### CODE REVIEW

**Comment by ncdc** [comment]
@shubheksha thanks for this! Would you please also update the comment above the field?

**Comment by shubheksha** [comment]
@ncdc, done!

**Comment by ncdc** [comment]
@shubheksha thanks, please squash & we'll merge when it passes CI

**Comment by skriss** [comment]
@wwitzel3 this can be backported too

**Pull request merged**
