### PR TITLE
Document CRD not found errors

### PR DESCRIPTION
**Pull request by nrb**
Will create a PR for the gh-pages branch once this content gets merged.

### CODE REVIEW

**Comment by ncdc** [comment]
Can we also change the error in the log to make it clearer that Ark's CRDs need to be installed?

**Comment by carlisia** [comment]
LGTM + Andy's comment. 👍

**Comment by nrb** [comment]
I like updating the error message, too.

Right now, it's an aggregated error reporting all CRDs that don't exist. I could either add to the aggregated error list, or just return it. Any preferences?

**Comment by carlisia** [comment]
@nrb I looked at the code and imo adding to the existing error list would be consistent with what's there already, and also useful to inform about all the missing CRDs at once, so this gets my vote.

**Comment by nrb** [comment]
Returned errors updated.

**Comment by carlisia** [comment]
Yes, I think this works well. 👍

**Comment by skriss** [comment]
LGTM

**Pull request merged**
