### PR TITLE
Use JSON merge patches everywhere

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <steve@heptio.com>

Unit tests pass but haven't tested manually yet.

### CODE REVIEW

**Comment by ncdc** [comment]
-4k lines of code, I like it!

**Comment by skriss** [comment]
Exercised all of the modified code paths and everything LGTM.

**Comment by skriss** [comment]
@ncdc this is ready for review/merge when you get a chance.

**Comment by ncdc** [comment]
If we want, we can keep the strategic merge patch for deployments (plugin add/remove).

**Comment by skriss** [comment]
Could, although then we don't get to delete ~4k lines of code :( Any particular reason not to switch those too?

**Comment by ncdc** [comment]
We'd need to look at what bits we're patching and see if the enhancements in strategic merge patch would be beneficial (see https://github.com/kubernetes/community/blob/master/contributors/devel/strategic-merge-patch.md).

**Comment by skriss** [comment]
I double-checked this and it looks like the json-patch library correctly assembles a JSON merge patch to handle list changes. Tested by repeatedly adding plugins, and the list correctly grows rather than being replaced each time. Same for removing plugins.

**Comment by ncdc** [comment]
Thanks for researching! LGTM.

**Pull request merged**
