### PR TITLE
Add events to nonRestorableResources and cohabitatingResources

### LINKED ISSUE #367: Permanently exclude restoring events
We back up but don't ever restore nodes. Should we consider doing the same with events?

cc @lypht @jrnt30 @jbeda @skriss @nrb @paulbouwer

### LINKED ISSUE #368: Need to handle cohabitation of events in core and events.k8s.io api groups
Need to modify `cohabitatingResources` in `pkg/backup/backup.go`. 1 group should be `""` (for core) and the other should be `events.k8s.io`.

### PR DESCRIPTION
**Pull request by sanketjpatel**
Fixes #367 
Fixes #368 

Signed-off-by: Sanket Patel <sanketpatel.301090@gmail.com>

### CODE REVIEW

**Comment by ncdc** [comment]
@sanketjpatel thanks for your PR! FYI I adjusted the description to change "addresses" to "fixes", as that makes GitHub close out the referenced issue when the PR is merged.

**Comment by ncdc** [comment]
@sanketjpatel ok I just tested this, and it did correctly exclude `events`... but they are actually cohabitating as `events.events.k8s.io` (see #368), so we'll also need to exclude `events.events.k8s.io`. Would you be able to make that change too please?

@skriss I wonder if we need to be a bit more integrated here, and have some connection between cohabitating resources and excluded resources?

**Comment by sanketjpatel** [comment]
Sure I'll update the PR! :)

**Comment by sanketjpatel** [comment]
Still have to do E2E test

**Comment by ncdc** [comment]
FYI GitHub requires each fixed issue have its own "Fixes" text, so
```
Fixes #367
Fixes #368
```

**Comment by ncdc** [comment]
We generate the cli references docs from the source code. `hack/update-generated-docs.sh` takes care of this. If you manually edit the docs, Travis will fail...

**Comment by ncdc** [comment]
@skriss please review - thx

**Pull request merged**
