### PR TITLE
Fix link to upgrade documentation in readme

### PR DESCRIPTION
**Pull request by danielcb**
The link to the upgrading to v0.10 docs was broken.

### CODE REVIEW

**Comment by nrb** [comment]
@skriss I think this is fine, since the README used by the site is in the `gh-pages` branch under the v0.10.0 directory.

**Comment by skriss** [comment]
OK, looking at other links on this page, this looks fine, however @danielcb can you move the link to a numbered footnote like all the other links on this page (not sure why this one was different), and include a leading `/` like links `[30]` and `[99]`?  The number you use for this one doesn't really matter as long as it's unique.  Thanks!!

**Comment by Bradamant3** [comment]
Yes, this change is fine. The doc-site-gen tooling we use strips the /docs directory prefix in the links, for the gh-pages site. Not sure why/how this one got stripped in the original, but many thanks to @danielcb for catching!

**Comment by skriss** [comment]
Alright I'm gonna merge this as-is so we get the link fixed, we can come back and move to a numbered link later.

**Pull request merged**
