### PR TITLE
Add note about kubeconfig in doc get-started.md

### PR DESCRIPTION
**Pull request by hex108**
Signed-off-by: Jun Gong <jungong@tencent.com>

I followed instructions in [get-started](https://heptio.github.io/ark/v0.10.0/get-started). When executing ark command, there is an error: `An error occurred: invalid configuration: no configuration has been provided`. In this PR, add a note for it.

### CODE REVIEW

**Comment by ncdc** [comment]
@hex108 thanks for your contribution! We already have this information in `docs/debugging-install.md`. Let's work with @Bradamant3 to figure out the best place to capture this information.

**Comment by Bradamant3** [comment]
@hex108 yes, this is a nice catch. But a more complete solution that also covers this case would be to add something like the following at l18 of `get-started.md`:
`If you encounter issues with installing or configuring, see [Debugging Installation Issues](debugging-install.md).`

**Comment by hex108** [comment]
Thanks @ncdc @Bradamant3 ! Just updated it.

**Comment by Bradamant3** [comment]
LGTM

**Pull request merged**
