### PR TITLE
Add correct link and change role

### PR DESCRIPTION
**Pull request by greggubarev**
Add correct link and change role from role/heptio-ark to role/<HEPTIO_ARK_ROLE_NAME>

### CODE REVIEW

**Comment by nrb** [comment]
Thanks for this @greggubarev! Would you mind adding a git sign off and pushing an update? `git commit amend --sign-off` should keep the same commit but add your sign off to the bottom.

**Comment by greggubarev** [comment]
> Thanks for this @greggubarev! Would you mind adding a git sign off and pushing an update? `git commit amend --sign-off` should keep the same commit but add your sign off to the bottom.

@nrb im added "Signed-off-by", or i do wrong? Sorry I do it for the first time

**Comment by nrb** [comment]
Almost! Our checker requires that every commit has a signed-off line, though. I'd recommend squashing this all into one commit (with `git rebase -i`), with a message that looks like this:

```
Add correct link and change role

Add correct link and change role from role/heptio-ark to role/<HEPTIO_ARK_ROLE_NAME>

Signed-off-by: Gregory Gubarev <g.gubarev63@gmail.com>
```

**Comment by greggubarev** [comment]
@nrb Done!

**Pull request merged**
