### PR TITLE
Support cross-compiling for clients

### PR DESCRIPTION
**Pull request by ncdc**
Add support for cross compiling clients.
Upgrade to go 1.9.

Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>

### CODE REVIEW

**Comment by ncdc** [comment]
retest this please

**Comment by ncdc** [comment]
I was just going to work on that. If you want to merge first I can do it after.

**Comment by ncdc** [comment]
I'll do the changes in this PR. I think it makes more sense than a follow-up.

**Comment by skriss** [comment]
WFM.

**Comment by skriss** [comment]
Do you want to include a change to the section I linked to above (to not have users run CLI in a container)? I suppose it won't really make sense until we actually publish the binaries so maybe we should just do it right before the release?

**Comment by ncdc** [comment]
Yeah I can do that. I think it's fine to include it.

**Comment by ncdc** [comment]
PTAL at the latest commit

**Comment by ncdc** [comment]
@davecheney @timothysc @fabioy FYI, if you're interested

**Comment by skriss** [comment]
LGTM, merging.

**Pull request merged**
