### PR TITLE
Document SignatureDoesNotMatch error and triaging

### LINKED ISSUE #714: Ticket 269: SignatureDoesNotMatch when getting logs from ceph bucket.
**What steps did you take and what happened:**
I setup ark to utilize the ceph object gateway.  I created a "backups" bucket and created an access_key_id and secret_access_key that I plugged into the ark config map along with the s3Url for the ceph gateway.

I can create a backup without any problem. I verified the backup completed with the "ark get backup <backup> command. I also verified the backup by posting a GET to the ceph bucket. However, when I run "ark backup logs <backup>,  I get an error stating the signature did not match.

**What did you expect to happen:**
When executing "ark backup logs <backup> I  expected to see the logs for the backup I created.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`

level=debug msg="Running processDownloadRequest" key=heptio-ark/backup5-20180730111323 logSource="pkg/controller/download_request_controller.go:190"

* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`

backup5   Completed   2018-07-28 21:43:22 -0500 CDT   28d       <none>

* `ark backup logs <backupname>`

An error occurred: request failed: <?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx00000000000000000017a-005b5f34fb-10eb-default</RequestId><HostId>10eb-default-default</HostId></Error>

* `ark restore describe <restorename>` or `kubectl get restore/<restorename> -n heptio-ark -o yaml`
* `ark restore logs <restorename>`

**Anything else you would like to add:**
I have a test cluster built with ark already deployed to the customer specs. I can also provide the ceph object gateway endpoint for testing purposes.

I am currently using ceph v10.2.9

It looks like v10.2.11 has some fixes for the signatureDoesNotMatch error.  I can upgrade ceph to the latest version if needed.

**Environment:**

- Ark version (use `ark version`): v0.8.1
- Kubernetes version (use `kubectl version`): v1.7.5
- Kubernetes installer & version: Kops v1.9.1
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 8 (jessie)

### PR DESCRIPTION
**Pull request by nrb**
Fixes #714

Signed-off-by: Nolan Brubaker <nolan@heptio.com>

### CODE REVIEW

**Comment by skriss** [comment]
I think I'd rather put this in the troubleshooting section (https://heptio.github.io/ark/v0.9.0/troubleshooting) -- could go on the main page, which could be reorganized to something like:

- General troubleshooting tips (ark commands, how to get debug logging)
- Debug installation/setup issues (under this section header, just include a link to the specific page)
- Debug restores (under this section header, just include a link to the specific page)
- Misc. issues (add this particular issue here)

WDYT?

**Comment by skriss** [comment]
I'd probably also move the `custom resource not found` item on the FAQ page into that misc. troubleshooting section :)

**Comment by nrb** [comment]
@skriss Moved the two mentioned errors into troubleshooting and did some reformatting so the links to other pages aren't lost.

**Comment by skriss** [comment]
LGTM

**Pull request merged**
