### PR TITLE
Change config CRD elements to server flags

### PR DESCRIPTION
**Pull request by carlisia**
Related to https://github.com/heptio/ark/pull/757

Signed-off-by: Carlisia <carlisia@grokkingtech.io>

### CODE REVIEW

**Comment by carlisia** [comment]
Incoming changes to this PR to reflect this improvement: https://github.com/heptio/ark/pull/757#discussion_r210336120

**Comment by skriss** [comment]
I think this needs another update

**Comment by carlisia** [comment]
Lemme double check.

**Comment by carlisia** [comment]
Good catch @skriss, I had to still remove the `in minutes`. Fixed.

**Comment by skriss** [comment]
OK so per slack discussion we don't need to manually do a PR for this - we'll run the heptio docs site generator when we cut v0.10.0 which will update the `gh-pages` branch with the contents of the `master` branch's `docs/` dir

**Comment by carlisia** [comment]
Copy that. Closing.

**Pull request closed without merging**
