### PR TITLE
add --default-backup-storage-location flag to server cmd

### LINKED ISSUE #750: Add a --default-backup-location flag to `ark server`, whose value defaults to "default"

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <steve@heptio.com>

Fixes #750

### CODE REVIEW

**Comment by skriss** [comment]
I always forget the make update.

**Comment by carlisia** [comment]
For the docs?

**Comment by carlisia** [comment]
Yeah (just looked up the build failure). I think it's gonna happen frequently to me too :)

**Comment by ncdc** [comment]
We should consider getting rid of those generated cli docs

**Comment by skriss** [comment]
Do y'all think the name of this flag is right? Should it be:

--default-storage-location
--default-backup-storage-location
--default-backup-location

Something else?

**Comment by ncdc** [comment]
Ok. I'd probably vote for `--default-backup-storage-location`

**Comment by skriss** [comment]
yeah, that's what I was thinking too

**Pull request merged**
