### PR TITLE
Add TAG_LATEST support to Makefile

### PR DESCRIPTION
**Pull request by ncdc**
Only tag an image as "latest" if TAG_LATEST is set to "true".

Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>

### CODE REVIEW

**Comment by ncdc** [comment]
@asenchi @skriss if I redirect the output from `git describe` to `/dev/null`, the overall `if` condition is always false. If you have suggestions for how to do this better, please share!

**Comment by asenchi** [comment]
> if I redirect the output from git describe to /dev/null, the overall if condition is always false. If you have suggestions for how to do this better, please share!

I think this is because you are using double brackets which considers an empty string "false". I'm not sure you even need the `&& ...` here as that a check to ensure we tagged latest on a release. The envvar accomplishes that now.

**Comment by ncdc** [comment]
@asenchi so you think the env var is entirely sufficient? WDYT @skriss @nrb ?

**Comment by asenchi** [comment]
At least as far as I understand it, I do think it is sufficient. Perhaps there is a situation I am missing.

**Comment by ncdc** [comment]
Since a human should be the one manually setting it to true, I'm ok removing the tag check.

**Comment by ncdc** [comment]
Updated

**Pull request merged**
