### PR TITLE
Example of using ThirdPartyResources instead of CustomResourceDefinit…

### PR DESCRIPTION
**Pull request by kellycampbell**
…ion for migrating a 1.6 cluster to 1.7

This is just an example for documenting what worked for me to migrate 1.6 clusters. It shouldn't be merged.

### CODE REVIEW

**Comment by ncdc** [comment]
@kellycampbell thanks! I think we can include this in the repo along with some docs that indicate if you're using 1.6 or earlier, you can try the TPR option, and go with CRDs for 1.7+. @abiogenesis-now could you please assist in determining how best to organize? Thanks!

**Comment by kellycampbell** [comment]
FYI, I didn't test if using TPR for the backup and CRD for the restore works. I tested restore on 1.7 using the same TPR deployment there.

**Comment by ncdc** [comment]
I would think that would be ok

**Comment by abiogenesis-now** [comment]
I'll take a look at this

**Comment by rosskukulinski** [comment]
@chuckbutler you might find this interesting

**Comment by chuckbutler** [comment]
Thanks @rosskukulinski, I'll pull this and give it a go later today on our 1.6 based cluster(s).

**Comment by chuckbutler** [comment]
Ah i had meant to circle back to  this yesterday. This works a treat on 1.6 clusters. I was able to backup on 1.6 and restore on both 1.6 and 1.7 without issue. 👍   (i didnt try going from CRD to TPR) but is suspect it'll work all the same as they are just schemas.

**Comment by ncdc** [comment]
> (i didnt try going from CRD to TPR) but I suspect it'll work all the same as they are just schemas.

If the TPR storage path in etcd is the same as it is for CRD, then hopefully yes.

@abiogenesis-now where would you like to see the TPR yaml go under examples?

**Comment by abiogenesis-now** [comment]
@ncdc Because the different combinations of PV/non-PV, TPR/CRD, and OS are getting ever-more convoluted in the instructions, I started working on a PR to autogenerate the proper YAML with ksonnet (and env variables), similarly to what Chuck and I attempted for Ark with https://github.com/heptio/sonobuoy/pull/58.  

If this TPR addition is extremely urgent, I can add it in now---however, I think I should be able to have a ksonnet PR out in the next day or two (with accompanying docs changes).

**Comment by ncdc** [comment]
It's not urgent

**Comment by ncdc** [comment]
I'm going to close this. If there's enough demand for a sample TPR yaml file in the repo, please let us  know and we'll figure out where to put it.

**Pull request closed without merging**
