### PR TITLE
Fix jenkins badge to display master branch status

### PR DESCRIPTION
**Pull request by ncdc**
Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>

### CODE REVIEW

**Comment by skriss** [comment]
Looks like this job has only run once? what needs to change to get it to build on PR merge?

**Comment by ncdc** [comment]
I had it misconfigured. It should be good to go now. We'll see on the next merge.

**Comment by skriss** [comment]
Ah, ok. Let's try it out with this one then. LGTM.

**Comment by ncdc** [comment]
It's working!

**Pull request merged**
