### PR TITLE
0.10 doc updates page

### PR DESCRIPTION
**Pull request by Bradamant3**
Signed-off-by: JENNIFER RONDEAU <jrondeau@heptio.com>

addresses issue #856 

I seem to have done something interesting with overlapping PRs. Will fix up after review as needed. This PR is for the new versions.md file only.

### CODE REVIEW

**Comment by skriss** [comment]
This LGTM, we'll just want to drop the first commit before merging since that's from PR #1004

**Comment by Bradamant3** [comment]
commit removed, but not ready to YOLO :-)

**Comment by skriss** [comment]
Are you planning to add a link to this page on the docs site nav?

**Comment by Bradamant3** [comment]
@skriss yes but that needs to be another PR against the gh-pages branch, until we move publication process (we'll have a new TOC altogether for 0.10 -- need entries for new CRDs info also)

**Pull request merged**
