### PR TITLE
upgrade to restic v0.9.3

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <steve@heptio.com>

### CODE REVIEW

**Comment by nrb** [comment]
Change looks fine, though should we call out any bug fixes/features for the new version, even if just in the commit for a changelog entry?

**Comment by nrb** [comment]
> I  just want to stay up-to-date so future upgrades span fewer versions.

Ok, that's fair. This also looks like it's not a point release, so the delta is hopefully small.

**Comment by skriss** [comment]
Yeah, looked at the notes and I don't think there's anything worth calling out.

**Comment by nrb** [comment]
@carlisia @wwitzel3 Would either of you mind reviewing and merging?

**Pull request merged**
