### PR TITLE
Move restic repos into the main Ark bucket, under restic/

### LINKED ISSUE #576: Enable sharing bucket between Ark and Restic
Right now Restic requires a separate bucket to be created with identical credentials as the main Ark server bucket.

For many users, having a separate bucket only makes the configuration & installation more complex.  Ark should allow sharing a bucket with Restic.

This would require creating root/parent-level directories to distinguish between backups and restic backup.  This would be a breaking change.

Perhaps we can link this with #103 which will also be having an impact on CRD compatibility.

### PR DESCRIPTION
**Pull request by skriss**
Fixes #576 

Note that this PR **requires** that restic share the main Ark bucket, not just *enables* it

### CODE REVIEW

**Comment by nrb** [comment]
Haven't read in depth yet, but thanks for providing docs with this! Does this change still send restic directly and only to the `default` backup storage location, or can it be directed to a different one?

**Comment by skriss** [comment]
This PR still only sends them to the default location.  I've got another branch on-deck to support multiple locations.

**Comment by nrb** [comment]
Walking through the migration steps again, somewhat unrelated comment:  L100 of `storage-layout-reorg-v0.10.md` says to execute the script step by step - if people are copying their commands into the terminal one at a time, the environment variables need to be `export`ed. I think that's going to be the primary method by which people interact with it, versus copying it into a file.

**Comment by skriss** [comment]
@carlisia @wwitzel3 would appreciate comments or a merge when you get a chance, thanks!

**Comment by wwitzel3** [comment]
Want to make sure I am following this correctly. We are removing the restic location and replacing it with a default under the new directory structure of `/restic`.

The rclone migration will move existing restic data to that location in our new expected format.

We no longer need to pass the restic location around because it is not determined by us, so if you enable restic, you can expect to see the `/restic` folder turn up.

**Comment by skriss** [comment]
@wwitzel3 correct on all counts

**Pull request merged**
