### PR TITLE
Bump alpine image for security fix

### PR DESCRIPTION
**Pull request by nrb**
This change includes the fix at https://github.com/docker-library/official-images/pull/4834

Signed-off-by: Nolan Brubaker <nolan@heptio.com>

### CODE REVIEW

**Comment by skriss** [comment]
@nrb do you want to include this in v0.9.6? As long as you've smoke-tested the new images I'm fine with it

**Comment by nrb** [comment]
@skriss Probably doesn't hurt. I confirmed the images build. Let me test the result in a cluster before we decide.

**Comment by nrb** [comment]
Tested, this appears to backup/restore correctly using this. There's a separate issue with the fsfreeze image, which I'll open a new PR for.

**Comment by skriss** [comment]
cool, thanks for testing!

**Pull request merged**
