### PR TITLE
shutdown gracefully on SIGINT/SIGTERM

### LINKED ISSUE #366: Clean up plugin processes on SIGINT when running locally
PR #334 made it possible to run the Ark server locally. However, when interrupting the server with ctrl-c, child processes such as the GCP object store plugin are not always cleaned up.

We should add a handler to kill any running plugin processes before exiting.

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <steve@heptio.com>

Fixes #366 

Currently we don't handle these signals. Per https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods, SIGTERM is sent when terminating a pod, and SIGINT is sent if running the server locally (i.e. for development) and ctrl+c is pressed.

### CODE REVIEW

**Comment by ncdc** [comment]
If we do something like this it terminates plugins on exit: https://gist.github.com/ncdc/c502eae499d63b0b1e445e8545d9b9f8

**Comment by skriss** [comment]
Nice - wasn't thinking about that. Added.

**Comment by ncdc** [comment]
This will fix #366

**Comment by nrb** [comment]
This makes sense to me. I'll give it a try later today.

**Comment by skriss** [comment]
@nrb did you get a chance to try this? Also @ncdc just a reminder of this given your plugin refactoring.

**Comment by ncdc** [comment]
It'll be fine to merge. I'm actually working on top of this.

**Comment by nrb** [comment]
@skriss Not yet - will fire it up against GKE now.

**Comment by ncdc** [comment]
LGTM

**Pull request merged**
