### PR TITLE
Added brew reference

### PR DESCRIPTION
**Pull request by omerlh**
Based on the answer to #1051, I thought it will be helpful for others to know about the formula :)

### CODE REVIEW

**Comment by nrb** [comment]
Thanks @omerlh! Would you mind amending the commit and adding a [sign off](https://git-scm.com/docs/git-commit#git-commit---signoff)?

**Comment by omerlh** [comment]
Done

**Comment by nrb** [comment]
LGTM, I'll let @Bradamant3 be the 2nd review.

**Comment by Bradamant3** [comment]
The only potential issue I see here is that this PR is against the 0.9 branch. We should probably take it against master, yes? (I can then backport it to the other versions for the doc site if you think it would be useful.)

**Comment by nrb** [comment]
Good catch, @Bradamant3. @omerlh mind doing this change against master and re-pushing? I changed in the GH UI, but unfortunately that included a ton of release-0.9 changes, so it'll need to be done against master manually.

**Comment by omerlh** [comment]
I think I used this branch because it's the default, I'll fix it

**Comment by skriss** [comment]
Closing this PR as it's been replaced by #1065

**Pull request closed without merging**
