### PR TITLE
Update to go 1.11

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by ncdc** [comment]
@gliptak thanks for this PR. We haven't updated our build image to use 1.11 yet. We should do them at the same time. That is in `hack/build-image/Dockerfile`. Would you be willing to make the change there too?

**Comment by gliptak** [comment]
@ncdc Thank you for the pointer I will push an update in a few

1.11.2-alpine3.8

https://hub.docker.com/_/golang/

**Comment by gliptak** [comment]
```Go 1.11``` needs ```gofmt```

https://travis-ci.org/heptio/ark/builds/457498491

**Comment by gliptak** [comment]
@ncdc the PR is green

**Comment by ncdc** [comment]
@gliptak thanks!

**Pull request merged**
