### PR TITLE
convert all controllers to use genericController, logContext -> log

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <steve@heptio.com>

Still need to do a little more manual testing

### CODE REVIEW

**Comment by skriss** [comment]
alright, ran through tests of all these controllers and everything seems to be working

**Comment by ncdc** [comment]
> I think it would be helpful to have a codified list of possible values for the first arg of newGenericController

I'd rather keep this open. That's in line w/how you create work queues (arbitrary names).

**Comment by carlisia** [comment]
Ah got it.

**Comment by skriss** [comment]
OK, good to go.

**Comment by nrb** [comment]
Will take a pass on this after lunch

**Pull request merged**
