### PR TITLE
get a new metadata accessor after calling backup item actions

### LINKED ISSUE #822: Restore of restic snapshot data broken in 0.9.2+
Hi Team,

kubernetes is installed on VMware, we have 1 master & 6 node cluster.
Currently we are using kubernetes 1.10 version.
We are storing backup data on AWS S3, but when we take backup with
` ark backup create ignite-backup --selector app=infra-distributed-db --snapshot-volumes`
It worked successfully with no errors but it is not taking pv data backup.
It is only taking config data backup .
here you can see the restic config.

```
kubectl describe daemonset restic -n heptio-ark
Name:           restic
Selector:       name=restic
Node-Selector:  <none>
Labels:         name=restic
Annotations:    kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"name":"restic","namespace":"heptio-ark"},"spec":{"selector":{"matchLabels":{"n...
Desired Number of Nodes Scheduled: 5
Current Number of Nodes Scheduled: 5
Number of Nodes Scheduled with Up-to-date Pods: 5
Number of Nodes Scheduled with Available Pods: 5
Number of Nodes Misscheduled: 0
Pods Status:  5 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           name=restic
  Service Account:  ark
  Containers:
   ark:
    Image:      gcr.io/heptio-images/ark:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      /ark
    Args:
      restic
      server
    Environment:
      NODE_NAME:                     (v1:spec.nodeName)
      HEPTIO_ARK_NAMESPACE:          (v1:metadata.namespace)
      AWS_SHARED_CREDENTIALS_FILE:  /credentials/cloud
      ARK_SCRATCH_DIR:              /scratch
    Mounts:
      /credentials from cloud-credentials (rw)
      /host_pods from host-pods (rw)
      /scratch from scratch (rw)
  Volumes:
   cloud-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cloud-credentials
    Optional:    false
   host-pods:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:  
   scratch:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
Events:      <none>
```

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <steve@heptio.com>

Fixes #822 

Manually tested/confirmed that this fixes the issue.  Now working on unit tests.

### CODE REVIEW

**Comment by skriss** [comment]
pushed a unit test that fails before the fix: https://travis-ci.org/heptio/ark/builds/426896179

**Comment by skriss** [comment]
now pushing the fix again

**Comment by bashofmann** [comment]
I also tested this patch manually and I can confirm that restic backups and restores are working again.

**Comment by nrb** [comment]
Given that this is preventing restores and some tight timelines for the team, I'm going to go ahead and merge this.

@skriss we'll need a backport to `release-0.9`, too.

**Pull request merged**
