### PR TITLE
update changelog for v0.10.0 GA release

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <steve@heptio.com>

### CODE REVIEW

**Comment by skriss** [comment]
@nrb yeah SGTM - if we merge it tonight I can create a v0.10.0 tag for @Bradamant3 to use for building the docs site

**Comment by nrb** [comment]
So long as the docs redirect don't point to v0.10 stuff too early with the latest release redirect :)

**Comment by skriss** [comment]
Yep - I assume she can get the PR ready but we won't merge it 'til tomorrow

**Comment by skriss** [comment]
good to merge?

**Pull request merged**
