### PR TITLE
Update current development changelog

### PR DESCRIPTION
**Pull request by wwitzel3**
Signed-off-by: Wayne Witzel III <wayne@riotousliving.com>

### CODE REVIEW

**Comment by skriss** [comment]
idk if we need to capture a changelog for docs changes - i don't think we really have in the past - WDYT?

**Comment by wwitzel3** [comment]
Yeah, I was kind of on auto pilot, just going through the merge commits since 0.10 release. I'll pull them out.

**Comment by nrb** [comment]
I think I agree with leaving them out for the most part. A big docs change might be worth putting in, but fixing broken links doesn't seem like it quite meets the bar.

**Comment by wwitzel3** [comment]
So with what @nrb said, should I leave in the update to our changelogs as an `Other Change`?

**Pull request merged**
