### PR TITLE
Enable restoring resources with ownerReference set

### PR DESCRIPTION
**Pull request by mwieczorek**
fixes: #816

### CODE REVIEW

**Comment by skriss** [comment]
Thanks for the PR @mwieczorek! We'll take a look at this over the next few days and provide any feedback.  We're all in meetings this week so may take a little longer than usual.

**Comment by nrb** [comment]
@mwieczorek Thanks for the contribution and sorry it's taken a bit to give you feedback.

A change went into master removing the cli reference docs - could you rebase on it and remove the change here?

**Comment by mwieczorek** [comment]
@nrb no problem. I deleted changes to md file and rebased.

**Comment by mwieczorek** [comment]
@nrb @skriss Can I do something else to make it merged? :)
btw: will it be in v0.10.0 or maybe in next 0.9.x patch release?

**Comment by ncdc** [comment]
LGTM

**Pull request merged**
