### PR TITLE
Remove cli reference docs generation

### LINKED ISSUE #798: Get rid of generated CLI docs
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently, we generate CLI documentation and store it in the repository.  This has questionable value and is a constant thorn in the side since contributors have to manually run `make update` to keep it updated, and builds fail if it's not updated.  We should remove the generated documentation and related steps from the build.

### PR DESCRIPTION
**Pull request by shubheksha**
This PR removes:
- cli reference docs folder
- scripts for updating and verifying docs

Fixes #798

### CODE REVIEW

**Comment by ncdc** [comment]
Thanks @shubheksha! I'm not seeing the Makefile change that you mentioned?

**Comment by shubheksha** [comment]
@ncdc, I didn't need to do that since I the `make update` actually runs all the update scripts, so I removed the script itself. I'll update the description

**Comment by ncdc** [comment]
You can also remove `docs/generate/ark.go`

**Comment by shubheksha** [comment]
@ncdc, done!

**Comment by ncdc** [comment]
Sorry, 1 more thing - if you run `dep ensure`, it should remove some packages we no longer need (that were only used as part of the docs generation).

**Comment by shubheksha** [comment]
@ncdc, done!

**Comment by ncdc** [comment]
LGTM. @skriss @nrb @carlisia @wwitzel3 - could 1 of you please 👀 ?

**Pull request merged**
