### PR TITLE
Make goimports consistent by pinning version and using -local flag

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
@carlisia I've updated the verify script to call the update script, so we don't duplicate the logic of finding files & calling gofmt and goimports. I also moved installing goimports into the build image's Dockerfile.

**Comment by ncdc** [comment]
@skriss ptal too

**Comment by carlisia** [comment]
This lgtm 👍

**Comment by nrb** [comment]
LGTM, though there's a merge conflict :(

**Comment by ncdc** [comment]
Fixing it

**Comment by ncdc** [comment]
Rebased

**Pull request merged**
